#!/bin/bash
echo "🔍 Verificando instalación del StateChart Editor..."
echo ""
echo "✅ Dependencias:"
npm list @xyflow/react react react-dom 2>/dev/null | grep -E "@xyflow|react" || echo "❌ Faltan dependencias"
echo ""
echo "✅ Archivos compilados:"
[ -f "out/statechart/stateChartEditor.js" ] && echo "  ✓ Extension compiled" || echo "  ✗ Extension NOT compiled"
[ -f "media/stateChartWebview.js" ] && echo "  ✓ Webview bundle exists" || echo "  ✗ Webview bundle MISSING"
echo ""
echo "✅ Archivos de ejemplo:"
ls -1 ../../examples/statecharts/*.statechart.json 2>/dev/null || echo "  ✗ No example files"
echo ""
echo "🚀 Para probar el editor:"
echo "  1. Abre VSCode en: /home/runtimevic/Descargas/trust-platform"
echo "  2. Presiona F5 para ejecutar la extensión en modo desarrollo"
echo "  3. En la ventana de desarrollo, abre: examples/statecharts/traffic-light.statechart.json"
echo "  4. El editor visual debería abrirse automáticamente"
echo ""
