#!/usr/bin/env bash
set -euo pipefail

MODE="${1:-run}"
BASELINE_FILE="${SALSA_HARDENING_BASELINE_FILE:-docs/reports/salsa-hardening-perf-baseline.env}"
SAMPLES="${SALSA_HARDENING_SAMPLES:-7}"
MAX_REGRESSION_PCT="${SALSA_HARDENING_MAX_REGRESSION_PCT:-5}"
WARMUP_RUNS="${SALSA_HARDENING_WARMUP_RUNS:-1}"

export ST_LSP_PERF_EDIT_LOOP_ITERS="${ST_LSP_PERF_EDIT_LOOP_ITERS:-120}"
export ST_LSP_PERF_EDIT_LOOP_AVG_MS="${ST_LSP_PERF_EDIT_LOOP_AVG_MS:-80}"
export ST_LSP_PERF_EDIT_LOOP_P95_MS="${ST_LSP_PERF_EDIT_LOOP_P95_MS:-140}"
export ST_LSP_PERF_EDIT_LOOP_CPU_MS="${ST_LSP_PERF_EDIT_LOOP_CPU_MS:-70}"

if ! [[ "$SAMPLES" =~ ^[1-9][0-9]*$ ]]; then
  echo "[salsa-hardening-perf] FAIL: SALSA_HARDENING_SAMPLES must be a positive integer"
  exit 1
fi
if ! [[ "$WARMUP_RUNS" =~ ^[0-9]+$ ]]; then
  echo "[salsa-hardening-perf] FAIL: SALSA_HARDENING_WARMUP_RUNS must be an integer >= 0"
  exit 1
fi

current_benchmark_id() {
  echo "trust-lsp.perf_edit_loop_budget.v2"
}

current_rustc_version() {
  if command -v rustc >/dev/null 2>&1; then
    rustc --version | sed -E 's/[^A-Za-z0-9._-]+/_/g'
  else
    echo "unknown"
  fi
}

current_lock_hash() {
  if [[ -f Cargo.lock ]]; then
    sha256sum Cargo.lock | awk '{print $1}'
  else
    echo "missing"
  fi
}

current_system() {
  uname -srm 2>/dev/null | sed -E 's/[^A-Za-z0-9._-]+/_/g' || echo "unknown"
}

extract_metric_series() {
  local file="$1"
  local key="$2"
  grep -Eo "${key}=[0-9]+(\\.[0-9]+)?" "$file" | cut -d '=' -f 2
}

metric_median() {
  local file="$1"
  local key="$2"
  extract_metric_series "$file" "$key" | sort -n | awk '
    { values[++n] = $1 }
    END {
      if (n == 0) {
        exit 2
      }
      if (n % 2 == 1) {
        print values[(n + 1) / 2]
      } else {
        printf "%.2f\n", (values[n / 2] + values[n / 2 + 1]) / 2
      }
    }
  '
}

metric_list() {
  local file="$1"
  local key="$2"
  extract_metric_series "$file" "$key" | paste -sd',' -
}

percent_change() {
  local baseline="$1"
  local current="$2"
  awk -v baseline="$baseline" -v current="$current" '
    BEGIN {
      if (baseline == 0) {
        printf "0.00"
      } else {
        printf "%.2f", ((current - baseline) / baseline) * 100
      }
    }
  '
}

run_samples() {
  local perf_log
  perf_log="$(mktemp)"
  trap 'rm -f "$perf_log"' RETURN

  for warmup in $(seq 1 "$WARMUP_RUNS"); do
    echo "[salsa-hardening-perf] warmup ${warmup}/${WARMUP_RUNS}"
    cargo test -p trust-lsp perf_edit_loop_budget -- --ignored --nocapture >/dev/null
  done

  : > "$perf_log"
  for sample in $(seq 1 "$SAMPLES"); do
    echo "[salsa-hardening-perf] sample ${sample}/${SAMPLES}"
    cargo test -p trust-lsp perf_edit_loop_budget -- --ignored --nocapture | tee -a "$perf_log"
  done

  CURRENT_AVG_MEDIAN="$(metric_median "$perf_log" "avg_ms")"
  CURRENT_P95_MEDIAN="$(metric_median "$perf_log" "p95_ms")"
  CURRENT_CPU_MEDIAN="$(metric_median "$perf_log" "cpu_ms_per_iter")"

  CURRENT_AVG_SAMPLES="$(metric_list "$perf_log" "avg_ms")"
  CURRENT_P95_SAMPLES="$(metric_list "$perf_log" "p95_ms")"
  CURRENT_CPU_SAMPLES="$(metric_list "$perf_log" "cpu_ms_per_iter")"
}

print_current_metrics() {
  echo "[salsa-hardening-perf] avg_samples=[${CURRENT_AVG_SAMPLES}] p95_samples=[${CURRENT_P95_SAMPLES}] cpu_samples=[${CURRENT_CPU_SAMPLES}]"
  echo "[salsa-hardening-perf] medians avg=${CURRENT_AVG_MEDIAN}ms p95=${CURRENT_P95_MEDIAN}ms cpu=${CURRENT_CPU_MEDIAN}ms/op"
}

record_baseline() {
  mkdir -p "$(dirname "$BASELINE_FILE")"
  local now
  local git_rev
  local benchmark_id
  local rustc_version
  local cargo_lock_sha256
  local system
  now="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  git_rev="$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")"
  benchmark_id="$(current_benchmark_id)"
  rustc_version="$(current_rustc_version)"
  cargo_lock_sha256="$(current_lock_hash)"
  system="$(current_system)"

  cat > "$BASELINE_FILE" <<EOF
# Generated by scripts/salsa_hardening_perf_gate.sh
recorded_at=${now}
git_rev=${git_rev}
benchmark_id=${benchmark_id}
rustc_version=${rustc_version}
cargo_lock_sha256=${cargo_lock_sha256}
system=${system}
samples=${SAMPLES}
avg_ms=${CURRENT_AVG_MEDIAN}
p95_ms=${CURRENT_P95_MEDIAN}
cpu_ms_per_iter=${CURRENT_CPU_MEDIAN}
avg_samples=${CURRENT_AVG_SAMPLES}
p95_samples=${CURRENT_P95_SAMPLES}
cpu_samples=${CURRENT_CPU_SAMPLES}
EOF

  echo "[salsa-hardening-perf] baseline recorded at ${BASELINE_FILE}"
}

compare_with_baseline() {
  if [[ ! -f "$BASELINE_FILE" ]]; then
    echo "[salsa-hardening-perf] FAIL: baseline file not found at ${BASELINE_FILE}"
    echo "[salsa-hardening-perf] Run: $0 record"
    exit 1
  fi

  # shellcheck disable=SC1090
  source "$BASELINE_FILE"

  if [[ "${SALSA_HARDENING_IGNORE_METADATA:-0}" != "1" ]]; then
    if ! validate_baseline_metadata; then
      echo "[salsa-hardening-perf] Run: $0 record"
      exit 1
    fi
  fi

  local baseline_avg="$avg_ms"
  local baseline_p95="$p95_ms"
  local baseline_cpu="$cpu_ms_per_iter"
  local fail=0

  compare_metric "avg_ms" "$baseline_avg" "$CURRENT_AVG_MEDIAN" || fail=1
  compare_metric "p95_ms" "$baseline_p95" "$CURRENT_P95_MEDIAN" || fail=1
  compare_metric "cpu_ms_per_iter" "$baseline_cpu" "$CURRENT_CPU_MEDIAN" || fail=1

  if [[ "$fail" -ne 0 ]]; then
    echo "[salsa-hardening-perf] FAIL: regression exceeded ${MAX_REGRESSION_PCT}%"
    exit 1
  fi

  echo "[salsa-hardening-perf] PASS: all metrics within ${MAX_REGRESSION_PCT}% regression budget"
}

compare_metric() {
  local label="$1"
  local baseline="$2"
  local current="$3"
  local delta
  delta="$(percent_change "$baseline" "$current")"
  echo "[salsa-hardening-perf] compare ${label}: baseline=${baseline} current=${current} delta=${delta}%"
  if awk -v delta="$delta" -v max="$MAX_REGRESSION_PCT" 'BEGIN { exit(delta > max) }'; then
    return 0
  fi
  return 1
}

validate_baseline_metadata() {
  local baseline_benchmark_id="${benchmark_id:-}"
  local baseline_rustc_version="${rustc_version:-}"
  local baseline_lock_hash="${cargo_lock_sha256:-}"
  local baseline_system="${system:-}"

  if [[ -z "$baseline_benchmark_id" || -z "$baseline_rustc_version" || -z "$baseline_lock_hash" || -z "$baseline_system" ]]; then
    echo "[salsa-hardening-perf] FAIL: baseline metadata missing (benchmark_id/rustc_version/cargo_lock_sha256/system)."
    return 1
  fi

  local expected_benchmark_id
  local expected_rustc_version
  local expected_lock_hash
  local expected_system
  expected_benchmark_id="$(current_benchmark_id)"
  expected_rustc_version="$(current_rustc_version)"
  expected_lock_hash="$(current_lock_hash)"
  expected_system="$(current_system)"

  local mismatch=0
  if [[ "$baseline_benchmark_id" != "$expected_benchmark_id" ]]; then
    echo "[salsa-hardening-perf] FAIL: benchmark_id mismatch (baseline=${baseline_benchmark_id}, current=${expected_benchmark_id})."
    mismatch=1
  fi
  if [[ "$baseline_rustc_version" != "$expected_rustc_version" ]]; then
    echo "[salsa-hardening-perf] FAIL: rustc_version mismatch (baseline=${baseline_rustc_version}, current=${expected_rustc_version})."
    mismatch=1
  fi
  if [[ "$baseline_lock_hash" != "$expected_lock_hash" ]]; then
    echo "[salsa-hardening-perf] FAIL: cargo_lock_sha256 mismatch (baseline=${baseline_lock_hash}, current=${expected_lock_hash})."
    mismatch=1
  fi
  if [[ "$baseline_system" != "$expected_system" ]]; then
    echo "[salsa-hardening-perf] FAIL: system mismatch (baseline=${baseline_system}, current=${expected_system})."
    mismatch=1
  fi

  if [[ "$mismatch" -ne 0 ]]; then
    echo "[salsa-hardening-perf] Baseline is stale for current benchmark environment."
    return 1
  fi

  return 0
}

run_samples
print_current_metrics

case "$MODE" in
  run)
    echo "[salsa-hardening-perf] PASS"
    ;;
  record)
    record_baseline
    ;;
  compare)
    compare_with_baseline
    ;;
  *)
    echo "Usage: $0 [run|record|compare]"
    exit 1
    ;;
esac
